<?php

namespace DistSys\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeTypeRepository extends EntityRepository {

  /**
   * Get AttributeTypes by Name
   * 
   * @param str $identifier
   * @param array $param
   * @return AttributeType
   */
  public function getByName($identifier = '', $param = NULL) {
    if ($param) {
      array_key_exists('limit', $param) ? $limit = (int) $param['limit'] : $limit = NULL;
      array_key_exists('offset', $param) ? $offset = (int) $param['offset'] : $offset = NULL;
      array_key_exists('order', $param) ? $order = (string) $param['order'] : $order = NULL;
    }
    $qb = $this->createQueryBuilder('at');
    $qb->select('at')
      ->where($qb->expr()->like('at.name', '?1'))
      ->setParameter(1, $identifier);

    if (isset($offset)) {
      $qb->setFirstResult($offset);
    }
    if (isset($limit)) {
      $qb->setMaxResults($limit);
    }
    if (isset($order)) {
      $qb->orderBy('at.name', $order);
    }

    return $qb->getQuery()->getResult();
  }

}
