<?php

namespace DistSys\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryItemRepository extends EntityRepository {



}
