# login zeugs
login:
    pattern:  /login
    defaults: { _controller: DistSysShopBundle:Security:login }
        
login_check:
    pattern:  /login_check

    
register:
    pattern:  /register
    defaults: { _controller: DistSysShopBundle:Security:register }
    
create:
    pattern:  /create
    defaults: { _controller: DistSysShopBundle:Security:create }
    

logout:
    pattern:  /logout
    defaults: { _controller: DistSysShopBundle:Security:logout }
    
# admin zeugs

admin_user:
    pattern: /admin/user    
    defaults: { _controller: DistSysShopBundle:Admin:user }
    
admin_user_edit:
    pattern: /admin/user/edit/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userEdit }
    
admin_user_update:
    pattern: /admin/user/update/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userUpdate }
    
admin_user_show:
    pattern: /admin/user/show/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userShow }
    
admin_user_remove:
    pattern: /admin/user/remove/{id}  
    defaults: { _controller: DistSysShopBundle:Admin:userRemove }
    
    
# profil zeugs   
    
user:
    pattern:  /user
    defaults: { _controller: DistSysShopBundle:User:index }
user_update:
    pattern:  /user/update
    defaults: { _controller: DistSysShopBundle:User:update }
    
user_password:
    pattern:  /user/password
    defaults: { _controller: DistSysShopBundle:User:password }
    
user_password_update:
    pattern:  /user/password/update
    defaults: { _controller: DistSysShopBundle:User:passwordUpdate }

# order zeugs

booking:
    pattern:  /booking
    defaults: { _controller: DistSysShopBundle:Booking:index }
    
#my_cart kann verändert werden, wenn nötig :)
my_cart:
  pattern: /myCart
  defaults: { _controller: DistSysShopBundle:Cart:index }
  
# shop zeug

category:
  pattern: /category/{categoryId}
  defaults: { _controller: DistSysShopBundle:Shop:category }
  requirements:
    productId: \d+

product:
  pattern: /product/{productId}
  defaults: { _controller: DistSysShopBundle:Shop:product }
  requirements:
    productId: \d+

home:
    pattern:  /{url}
    defaults: { _controller: DistSysShopBundle:Default:index, url: 'frontpage' }
