# login zeugs
login:
    pattern:  /login
    defaults: { _controller: DistSysShopBundle:Security:login }
        
login_check:
    pattern:  /login_check

    
register:
    pattern:  /register
    defaults: { _controller: DistSysShopBundle:Security:register }
    
create:
    pattern:  /create
    defaults: { _controller: DistSysShopBundle:Security:create }
    

logout:
    pattern:  /logout
    defaults: { _controller: DistSysShopBundle:Security:logout }
    
# profil zeugs   
    
user:
    pattern:  /user
    defaults: { _controller: DistSysShopBundle:User:index }
user_update:
    pattern:  /user/update
    defaults: { _controller: DistSysShopBundle:User:update }
    
user_password:
    pattern:  /user/password
    defaults: { _controller: DistSysShopBundle:User:password }
    
user_password_update:
    pattern:  /user/password/update
    defaults: { _controller: DistSysShopBundle:User:passwordUpdate }

# order zeugs

booking:
    pattern:  /booking
    defaults: { _controller: DistSysShopBundle:Booking:index }

    
my_cart:
  pattern: /myCart
  defaults: { _controller: DistSysShopBundle:Cart:index }

home:
    pattern:  /
    defaults: { _controller: DistSysShopBundle:Default:index, url: 'frontpage' }