dist_sys_shop_homepage:
    pattern:  /
    defaults: { _controller: DistSysShopBundle:Default:index, url: 'frontpage' }
  

login:
    pattern:  /login
    defaults: { _controller: DistSysShopBundle:Security:login }
        
login_check:
    pattern:  /login_check

    
register:
    pattern:  /register
    defaults: { _controller: DistSysShopBundle:Security:register }
    

logout:
    pattern:  /logout
    defaults: { _controller: DistSysShopBundle:Security:logout }

