# login zeugs
login:
    pattern:  /login
    defaults: { _controller: DistSysShopBundle:Security:login }
        
login_check:
    pattern:  /login_check

    
register:
    pattern:  /register
    defaults: { _controller: DistSysShopBundle:Security:register }
    
create:
    pattern:  /create
    defaults: { _controller: DistSysShopBundle:Security:create }
    

logout:
    pattern:  /logout
    defaults: { _controller: DistSysShopBundle:Security:logout }
    
# admin zeugs

admin_user:
    pattern: /admin/user    
    defaults: { _controller: DistSysShopBundle:Admin:user }
    
admin_user_part:
    pattern: /admin/user/part    
    defaults: { _controller: DistSysShopBundle:Admin:userPart }
    
admin_user_edit:
    pattern: /admin/user/edit/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userEdit }
    
admin_user_update:
    pattern: /admin/user/update/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userUpdate }
    
admin_user_show:
    pattern: /admin/user/show/{id}
    defaults: { _controller: DistSysShopBundle:Admin:userShow }
    
admin_user_remove:
    pattern: /admin/user/remove/{id}  
    defaults: { _controller: DistSysShopBundle:Admin:userRemove }
    
    
admin_categorie:
    pattern: /admin/categorie    
    defaults: { _controller: DistSysShopBundle:Admin:categorie }
    
admin_categorie_part:
    pattern: /admin/categorie/part  
    defaults: { _controller: DistSysShopBundle:Admin:categoriePart }
    
admin_categorie_new:
    pattern: /admin/categorie/new    
    defaults: { _controller: DistSysShopBundle:Admin:categorieNew }
    
admin_categorie_save:
    pattern: /admin/categorie/save    
    defaults: { _controller: DistSysShopBundle:Admin:categorieSave }
    
admin_categorie_edit:
    pattern: /admin/categorie/edit/{id}
    defaults: { _controller: DistSysShopBundle:Admin:categorieEdit }
    
admin_categorie_update:
    pattern: /admin/categorie/update/{id}
    defaults: { _controller: DistSysShopBundle:Admin:categorieUpdate }
    
admin_categorie_show:
    pattern: /admin/categorie/show/{id}
    defaults: { _controller: DistSysShopBundle:Admin:categorieShow }
    
admin_categorie_remove:
    pattern: /admin/categorie/remove/{id}  
    defaults: { _controller: DistSysShopBundle:Admin:categorieRemove }
    
    
admin_product:
    pattern: /admin/product    
    defaults: { _controller: DistSysShopBundle:Admin:product }
    
admin_product_part:
    pattern: /admin/product/part  
    defaults: { _controller: DistSysShopBundle:Admin:productPart }
    
admin_product_new:
    pattern: /admin/product/new    
    defaults: { _controller: DistSysShopBundle:Admin:productNew }
    
admin_product_save:
    pattern: /admin/product/save    
    defaults: { _controller: DistSysShopBundle:Admin:productSave }
    
admin_product_edit:
    pattern: /admin/product/edit/{id}
    defaults: { _controller: DistSysShopBundle:Admin:productEdit }
    
admin_product_update:
    pattern: /admin/product/update/{id}
    defaults: { _controller: DistSysShopBundle:Admin:productUpdate }
    
admin_product_show:
    pattern: /admin/product/show/{id}
    defaults: { _controller: DistSysShopBundle:Admin:productShow }
    
admin_product_remove:
    pattern: /admin/product/remove/{id}  
    defaults: { _controller: DistSysShopBundle:Admin:productRemove }
    
    
# profil zeugs   
    
user:
    pattern:  /user
    defaults: { _controller: DistSysShopBundle:User:index }
user_update:
    pattern:  /user/update
    defaults: { _controller: DistSysShopBundle:User:update }
    
user_password:
    pattern:  /user/password
    defaults: { _controller: DistSysShopBundle:User:password }
    
user_password_update:
    pattern:  /user/password/update
    defaults: { _controller: DistSysShopBundle:User:passwordUpdate }

# order zeugs

booking:
    pattern:  /booking
    defaults: { _controller: DistSysShopBundle:Booking:index }
    
#my_cart kann verändert werden, wenn nötig :)
my_cart:
  pattern: /myCart
  defaults: { _controller: DistSysShopBundle:Cart:index }
  
cartChange:
  pattern: /cart/change/{productId}
  defaults: { _controller: DistSysShopBundle:Cart:change }
  
  
cartRemove:
  pattern: /cart/remove/{productId}
  defaults: { _controller: DistSysShopBundle:Cart:remove }
add_cart:
  pattern: /cart/add/{productId}
  defaults: { _controller: DistSysShopBundle:Cart:add }
  
  
# shop zeug

category:
  pattern: /category/{categoryId}
  defaults: { _controller: DistSysShopBundle:Shop:category }
  requirements:
    productId: \d+
    
category_part:
  pattern: /categoryPart/{categoryId}
  defaults: { _controller: DistSysShopBundle:Shop:categoryPart }
  requirements:
    productId: \d+

product:
  pattern: /product/{productId}
  defaults: { _controller: DistSysShopBundle:Shop:product }
  requirements:
    productId: \d+

home:
    pattern:  /{url}
    defaults: { _controller: DistSysShopBundle:Default:simpleSite, url: 'frontpage' }
    
    
default:
    pattern:  /
    defaults: { _controller: DistSysShopBundle:Default:index }
