DistSys\ShopBundle\Entity\Attribute:
  
  type: entity
  
  table: attributes
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    name:
      type: string

  manyToOne:
    attributeType:
      targetEntity: AttributeType
      inversedBy: attributes
      
  manyToMany:
    products:
      targetEntity: Product
      mappedBy: attributes