DistSys\ShopBundle\Entity\AttributeType:
  
  type: entity
  
  table: attributeTypes
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    name:
      type: string
      nullable: false
      
  oneToMany:
    attributes:
      targetEntity: Attribute
      mappedBy: id
      cascade: ["all"]