DistSys\ShopBundle\Entity\BookingItem:
  
  type: entity
  
  table: bookingitems
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    quatity:
      type: integer

  manyToOne:
    booking:
      targetEntity: Booking
      inversedBy: bookingItems
    product:
      targetEntity: Product
      inversedBy: bookingItem