DistSys\ShopBundle\Entity\Product:
  
  type: entity
  repositoryClass: DistSys\ShopBundle\Entity\Repository\ProductRepository
  
  table: products
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    name:
      type: string
      nullable: false
    description:
      type: text
    price:
      type: decimal
      scale: 2
      nullable: false
    stock:
      type: integer
      unsigned: true
      nullable: false
    status:
      type: boolean

  oneToMany:
    galleryItems:
      targetEntity: GalleryItem
      mappedBy: id
    bookingItems:
      targetEntity: BookingItem
      mappedBy: id

  manyToMany:
    attributes:
      targetEntity: Attribute
      inversedBy: products
      joinTable:
        name: attributesToProducts
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          attribute_id:
            referencedColumnName: id
            