DistSys\ShopBundle\Entity\Role:
  
  type: entity
  
  table: roles
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    name:
      type: string

  manyToMany:
    users:
      targetEntity: User
      mappedBy: roles