DistSys\ShopBundle\Entity\SimpleSite:
  
  type: entity
  
  table: simpleSite
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    content:
      type: text
      nullable: false
    title:
      type: string
      nullable: false