DistSys\ShopBundle\Entity\User:
  
  type: entity
  repositoryClass: DistSys\ShopBundle\Entity\UserRepository
  table: users
  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  fields:
    username:
      type: string
      nullable: false
    email:
      type: string
      unique: true
      nullable: false
    salt:
      type: string
      unique: true
      nullable: false
    firstname:
      type: string
      nullable: true
    lastname:
      type: string
      nullable: true
    male:
      type: boolean
      nullable: true
    street:
      type: string
      nullable: true
    postal:
      type: string
      nullable: true
    city:
      type: string
      nullable: true
    phone:
      type: string
    password:
      type: string
      nullable: false
      
  oneToMany:
    bookings:
      targetEntity: Booking
      mappedBy: id
      cascade: ["all"]
      
  manyToMany:
    roles:
      targetEntity: Role
      inversedBy: users
      joinTable:
        name: rolesToUsers
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          role_id:
            referencedColumnName: id